openapi: 3.0.3
info:
  title: Haggis Game API
  version: 1.0.0
  description: API do tworzenia gry karcianej Haggis oraz pobierania jej stanu.

servers:
  - url: https://api.example.com

tags:
  - name: Games
    description: Operacje na grach

paths:
  /games:
    post:
      tags: [Games]
      summary: Utwórz nową grę
      operationId: createGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateGameRequest"
            examples:
              threePlayers:
                value:
                  players:
                    - id: piotr
                      displayName: Piotr
                      type: Human
                    - id: slawek
                      displayName: Sławek
                      type: AI
                      aiProfile: MonteCarlo
                    - id: robert
                      displayName: Robert
                      type: AI
                      aiProfile: MonteCarlo
                  rules:
                    seed: 12345
                    maxPlayers: 3
                  options:
                    includeHandsInState: false
      responses:
        "201":
          description: Gra utworzona
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateGameResponse"
        "400":
          description: Błędne dane wejściowe
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

  /games/{gameId}:
    get:
      tags: [Games]
      summary: Pobierz stan gry
      operationId: getGameState
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
            minLength: 1
        - name: view
          in: query
          required: false
          description: |
            Kontroluje „widok” stanu:
            - Public: bez rąk graczy (dla widzów / przeciwników)
            - Player: z ręką tylko konkretnego gracza (wymaga playerId)
            - Debug: pełen stan (np. dla dev)
          schema:
            type: string
            enum: [Public, Player, Debug]
            default: Public
        - name: playerId
          in: query
          required: false
          description: Wymagane, jeśli view=Player
          schema:
            type: string
      responses:
        "200":
          description: Aktualny stan gry
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameState"
        "404":
          description: Gra nie istnieje
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "400":
          description: Błędne parametry (np. view=Player bez playerId)
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

components:
  schemas:
    CreateGameRequest:
      type: object
      required: [players]
      properties:
        players:
          type: array
          minItems: 2
          maxItems: 3
          items:
            $ref: "#/components/schemas/PlayerSpec"
        rules:
          $ref: "#/components/schemas/GameRules"
        options:
          $ref: "#/components/schemas/CreateGameOptions"

    CreateGameOptions:
      type: object
      additionalProperties: false
      properties:
        includeHandsInState:
          type: boolean
          default: false
          description: Jeśli true, API może zwracać ręce w stanie gry (raczej do debug/dev).

    CreateGameResponse:
      type: object
      required: [gameId, createdAt, state]
      properties:
        gameId:
          type: string
        createdAt:
          type: string
          format: date-time
        state:
          $ref: "#/components/schemas/GameState"

    PlayerSpec:
      type: object
      required: [id, displayName, type]
      additionalProperties: false
      properties:
        id:
          type: string
          description: Stabilny identyfikator gracza (np. 'piotr', 'ai-1')
          minLength: 1
        displayName:
          type: string
          minLength: 1
        type:
          $ref: "#/components/schemas/PlayerType"
        aiProfile:
          type: string
          description: Opcjonalne dla AI (np. MonteCarlo, Random, Heuristic)
          example: MonteCarlo

    PlayerType:
      type: string
      enum: [Human, AI]

    GameRules:
      type: object
      additionalProperties: false
      properties:
        seed:
          type: integer
          format: int64
          description: Seed do deterministycznego tasowania (ułatwia testy).
        maxPlayers:
          type: integer
          format: int32
          minimum: 2
          maximum: 3
          default: 3

    GameState:
      type: object
      required: [gameId, status, players, turn, table, scores, updatedAt]
      properties:
        gameId:
          type: string
        status:
          $ref: "#/components/schemas/GameStatus"
        players:
          type: array
          minItems: 2
          maxItems: 3
          items:
            $ref: "#/components/schemas/PlayerState"
        turn:
          $ref: "#/components/schemas/TurnState"
        table:
          $ref: "#/components/schemas/TableState"
        scores:
          $ref: "#/components/schemas/ScoreState"
        updatedAt:
          type: string
          format: date-time

    GameStatus:
      type: string
      enum: [WaitingForStart, InProgress, Finished]

    PlayerState:
      type: object
      required: [id, displayName, type, handCount, isEliminated]
      additionalProperties: false
      properties:
        id:
          type: string
        displayName:
          type: string
        type:
          $ref: "#/components/schemas/PlayerType"
        handCount:
          type: integer
          format: int32
          minimum: 0
          description: Ile kart ma na ręce (publiczna informacja).
        hand:
          type: array
          description: |
            Opcjonalne – obecne tylko, jeśli backend pozwala zwracać rękę (view=Player albo Debug).
          items:
            $ref: "#/components/schemas/Card"
        isEliminated:
          type: boolean

    TurnState:
      type: object
      required: [currentPlayerId, phase, trickNumber]
      additionalProperties: false
      properties:
        currentPlayerId:
          type: string
        phase:
          type: string
          enum: [Play, Pass, Resolve]
        trickNumber:
          type: integer
          format: int32
          minimum: 1
        lastAction:
          $ref: "#/components/schemas/LastAction"

    LastAction:
      type: object
      additionalProperties: false
      properties:
        type:
          type: string
          enum: [Play, Pass, StartGame]
        byPlayerId:
          type: string
        playedCards:
          type: array
          items:
            $ref: "#/components/schemas/Card"
        at:
          type: string
          format: date-time

    TableState:
      type: object
      required: [currentTrick, pile]
      additionalProperties: false
      properties:
        currentTrick:
          $ref: "#/components/schemas/Trick"
        pile:
          type: array
          description: Zebrane tricki / stos odrzuconych (jeśli chcesz to ujawniać).
          items:
            $ref: "#/components/schemas/Trick"

    Trick:
      type: object
      required: [plays]
      additionalProperties: false
      properties:
        plays:
          type: array
          items:
            $ref: "#/components/schemas/TrickPlay"
        leadingPlayerId:
          type: string
          nullable: true
        trickType:
          type: string
          nullable: true
          description: Np. Single, Pair, Sequence, Bomb... (jeśli to u siebie klasyfikujesz)

    TrickPlay:
      type: object
      required: [playerId, cards]
      additionalProperties: false
      properties:
        playerId:
          type: string
        cards:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Card"

    ScoreState:
      type: object
      additionalProperties: false
      properties:
        pointsByPlayerId:
          type: object
          additionalProperties:
            type: integer
            format: int32
        winnerPlayerId:
          type: string
          nullable: true

    Card:
      type: object
      required: [code]
      additionalProperties: false
      properties:
        code:
          type: string
          description: |
            Kod karty w formacie ustalonym przez silnik.
            Przykład: "5H" = 5 Kier, "JD" = Walet Karo.
            Dla Haggis możesz też mieć specjalne: J/Q/K jako dzikie.
          example: "5H"
        suit:
          type: string
          nullable: true
          enum: [Clubs, Diamonds, Hearts, Spades]
        rank:
          type: string
          nullable: true
          description: "2..10,J,Q,K,A lub inny system jeśli masz własny"
        isWild:
          type: boolean
          nullable: true

    ProblemDetails:
      type: object
      required: [title, status]
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string




